import { Disclosure, Transition } from "@headlessui/react";
import Image from "next/image";
import Link from "next/link";
import ChevronDown from "public/icons/chevronDown.svg";
import TwitterMobile from "public/icons/twitterMobile.svg";
import EmailMobile from "public/icons/emailMobile.svg";
import CalendlyMobile from "public/icons/calendlyMobile.svg";

const MainPage6Mobile = () => {
  return (
    <>
      <div className="relative w-full bg-[#F5F3EF] py-[60px] px-[20px]">
        <div className="mx-auto font-bold text-[18px] leading-[29px] xsm:text-[24px] xsm:leading-[34px] sm:text-[36px] sm:leading-[51px] text-center">
          Frequently Asked Questions
        </div>
        <div className="mt-[40px] flex flex-col gap-y-[12px] ">
          <Disclosure>
            <Disclosure.Button className="mx-auto max-w-[922px] w-full bg-white rounded-[24px] p-[16px] ui-open:px-[15px] ui-open:border-[1px] ui-open:border-blue ui-open:bg-[#F5F9FF] ui-open:shadow-[0px_8px_28px_rgba(20,20,43,0.1)]">
              <div className="flex justify-between items-center">
                <div className="font-bold text-black text-[15px] leading-[21px] xsm:text-[16px] xsm:leading-[22px] max-w-[80%] text-start">
                  What is the difference between NFTFi (P2P) and BendDAO
                  (P2Pool)?
                </div>

                <div className="w-[24px] h-[24px] sm:w-[28px] sm:h-[28px] bg-[#F5F3EF] ui-open:bg-blue rounded-[50%] flex justify-center items-center">
                  <ChevronDown className="ui-open:stroke-white ui-open:rotate-180 stroke-black" />
                </div>
              </div>
              <Transition
                enter="transition duration-400 ease-out"
                enterFrom="transform scale-95 opacity-0"
                enterTo="transform scale-100 opacity-100"
              >
                <Disclosure.Panel className="font-normal text-black text-[14px] leading-[20px] mt-[8px] text-start">
                  Bancof combines the strengths of both models: lenders acquire
                  the NFT in case of loan default (like P2P), and benefit from
                  an automated process that eliminates manual parameter
                  management (like P2Pool).
                </Disclosure.Panel>
              </Transition>
            </Disclosure.Button>
          </Disclosure>
          <Disclosure>
            <Disclosure.Button className="mx-auto max-w-[922px] w-full bg-white rounded-[24px] p-[16px] ui-open:px-[15px] ui-open:border-[1px] ui-open:border-blue ui-open:bg-[#F5F9FF] ui-open:shadow-[0px_8px_28px_rgba(20,20,43,0.1)]">
              <div className="flex justify-between items-center">
                <div className="font-bold text-black text-[15px] leading-[21px] xsm:text-[16px] xsm:leading-[22px] max-w-[80%] text-start">
                  Can I modify the parameters of the loan when the loan pool is
                  already live?
                </div>

                <div className="w-[24px] h-[24px] sm:w-[28px] sm:h-[28px] bg-[#F5F3EF] ui-open:bg-blue rounded-[50%] flex justify-center items-center">
                  <ChevronDown className="ui-open:stroke-white ui-open:rotate-180 stroke-black" />
                </div>
              </div>

              <Transition
                enter="transition duration-400 ease-out"
                enterFrom="transform scale-95 opacity-0"
                enterTo="transform scale-100 opacity-100"
              >
                <Disclosure.Panel className="font-normal text-black text-[14px] leading-[20px] mt-[8px] text-start">
                  Yes, admin of the loan pool can change the loan parameters but
                  active loans that have already been issued will be unaffected
                  by the changes. Additional gas fee generated by the
                  modifications of the loan parameters will need to be taken
                  care of by the admin of the loan pool.
                </Disclosure.Panel>
              </Transition>
            </Disclosure.Button>
          </Disclosure>
          <Disclosure>
            <Disclosure.Button className="mx-auto max-w-[922px] w-full bg-white rounded-[24px] p-[16px] ui-open:px-[15px] ui-open:border-[1px] ui-open:border-blue ui-open:bg-[#F5F9FF] ui-open:shadow-[0px_8px_28px_rgba(20,20,43,0.1)]">
              <div className="flex justify-between items-center">
                <div className="font-bold text-black text-[15px] leading-[21px] xsm:text-[16px] xsm:leading-[22px] max-w-[80%] text-start">
                  Can we open loan pools only funded by the community treasury?
                </div>

                <div className="w-[24px] h-[24px] sm:w-[28px] sm:h-[28px] bg-[#F5F3EF] ui-open:bg-blue rounded-[50%] flex justify-center items-center">
                  <ChevronDown className="ui-open:stroke-white ui-open:rotate-180 stroke-black" />
                </div>
              </div>
              <Transition
                enter="transition duration-400 ease-out"
                enterFrom="transform scale-95 opacity-0"
                enterTo="transform scale-100 opacity-100"
              >
                <Disclosure.Panel className="font-normal text-black text-[14px] leading-[20px] mt-[8px] text-start">
                  Not necessarily. Loan pools generated by Bancof tool can be
                  funded by individual whales as well. Some communities will opt
                  to partially fund loan pools from the community treasury and
                  open LP allocation to individual community members.
                </Disclosure.Panel>
              </Transition>
            </Disclosure.Button>
          </Disclosure>
          <Disclosure>
            <Disclosure.Button className="mx-auto max-w-[922px] w-full bg-white rounded-[24px] p-[16px] ui-open:px-[15px] ui-open:border-[1px] ui-open:border-blue ui-open:bg-[#F5F9FF] ui-open:shadow-[0px_8px_28px_rgba(20,20,43,0.1)]">
              <div className="flex justify-between items-center">
                <div className="font-bold text-black text-[15px] leading-[21px] xsm:text-[16px] xsm:leading-[22px] max-w-[80%] text-start">
                  Can we customize the looks and feels of our dashboard?
                </div>

                <div className="w-[24px] h-[24px] sm:w-[28px] sm:h-[28px] bg-[#F5F3EF] ui-open:bg-blue rounded-[50%] flex justify-center items-center">
                  <ChevronDown className="ui-open:stroke-white ui-open:rotate-180 stroke-black" />
                </div>
              </div>
              <Transition
                enter="transition duration-400 ease-out"
                enterFrom="transform scale-95 opacity-0"
                enterTo="transform scale-100 opacity-100"
              >
                <Disclosure.Panel className="font-normal text-black text-[14px] leading-[20px] mt-[8px] text-start">
                  Yes, for the launching partners, our design team can customize
                  the looks and feels of the loan dashboard so it fits the
                  community&apos;s brand identity. If a community wishes more
                  detailed design customization, please contact team@bancof.io.
                </Disclosure.Panel>
              </Transition>
            </Disclosure.Button>
          </Disclosure>
          <Disclosure>
            <Disclosure.Button className="mx-auto max-w-[922px] w-full bg-white rounded-[24px] p-[16px] ui-open:px-[15px] ui-open:border-[1px] ui-open:border-blue ui-open:bg-[#F5F9FF] ui-open:shadow-[0px_8px_28px_rgba(20,20,43,0.1)]">
              <div className="flex justify-between items-center">
                <div className="font-bold text-black text-[15px] leading-[21px] xsm:text-[16px] xsm:leading-[22px] max-w-[80%] text-start">
                  Who holds the control of the loan pool created?
                </div>

                <div className="w-[24px] h-[24px] sm:w-[28px] sm:h-[28px] bg-[#F5F3EF] ui-open:bg-blue rounded-[50%] flex justify-center items-center">
                  <ChevronDown className="ui-open:stroke-white ui-open:rotate-180 stroke-black" />
                </div>
              </div>
              <Transition
                enter="transition duration-400 ease-out"
                enterFrom="transform scale-95 opacity-0"
                enterTo="transform scale-100 opacity-100"
              >
                <Disclosure.Panel className="font-normal text-black text-[14px] leading-[20px] mt-[8px] text-start">
                  Each loan pool contract is a separate contract, and each
                  deployer is the authorized owner of their respective contract,
                  guaranteeing security and autonomy to the respective owners of
                  the loan pool.
                  <br />
                  Bancof team at no point has access to any asset or the pool
                  contract deployed.
                </Disclosure.Panel>
              </Transition>
            </Disclosure.Button>
          </Disclosure>
        </div>
      </div>
      <div className="relative w-full py-[40px] px-[10px] xsm:px-[20px] bg-blue">
        <div className="flex flex-col gap-y-[20px] items-center">
          <span className="font-bold text-white text-[20px] leading-[30px] xsm:text-[24px] xsm:leading-[34px] sm:text-[36px] sm:leading-[51px] text-center">
            Get in touch 🤝 with Bancof
          </span>
          <div className="flex xsm:gap-x-[8px] gap-x-[6px]">
            <Link
              href="https://twitter.com/Bancof_"
              target="_blank"
              rel="noreferrer"
            >
              <div className=" cursor-pointer bg-white rounded-[20px] p-[10px] xsm:p-[12px] flex flex-col items-center">
                <div className="xsm:px-[25px] px-[16px]">
                  <TwitterMobile className="scale-[0.875] xsm:scale-[1]" />
                </div>
                <span className="text-[14px] xsm:text-[16px] text-blue font-bold leading-[28px]">
                  Twitter
                </span>
              </div>
            </Link>
            <Link href="mailto:team@bancof.io" target="_blank" rel="noreferrer">
              <div className=" cursor-pointer bg-white rounded-[20px] p-[10px] xsm:p-[12px] flex flex-col items-center">
                <div className="xsm:px-[25px] px-[16px]">
                  <EmailMobile className="scale-[0.875] xsm:scale-[1]" />
                </div>
                <span className="text-[14px] xsm:text-[16px] text-blue font-bold leading-[28px]">
                  E-mail
                </span>
              </div>
            </Link>

            <Link
              href="https://calendly.com/julia-bancof/meeting-call?back=1&month=2023-05"
              target="_blank"
              rel="noreferrer"
            >
              <div className=" cursor-pointer bg-white rounded-[20px] p-[10px] xsm:p-[12px] flex flex-col items-center">
                <div className="xsm:px-[25px] px-[16px]">
                  <CalendlyMobile className="scale-[0.875] xsm:scale-[1]" />
                </div>
                <span className="text-[14px] xsm:text-[16px] text-blue font-bold leading-[28px]">
                  Calendly
                </span>
              </div>
            </Link>
          </div>
        </div>
      </div>
      <div className="relative w-full bg-[#383F4D] py-[20px] flex flex-col items-center">
        <Image src="/icons/safe.svg" width={32} height={32} alt="safe" />
        <div className="mt-[12px] font-normal text-white text-[16px] leading-[28px] sm:text-[24px] sm:leading-[42px] text-center">
          <span>
            Running SAFE for 365 days.
            <br />
            Read more in the&nbsp;
          </span>
          <Link
            href="/audit/PeckShield-Audit-Report-Bancof-v1.0.pdf"
            target="_blank"
            rel="noreferrer"
          >
            <span className="underline underline-offset-2">Audit report</span>
          </Link>
        </div>
      </div>
    </>
  );
};
export default MainPage6Mobile;
